#!/usr/bin/env python3
"""Generate a compact, visual README.md from ecosystem.json.

The README is intentionally a bird's-eye view: one row per top-level
cluster showing its sub-areas and a handful of example projects. The
full, exhaustive tree lives in SCHEMA.md (generated by
generate_schema.py) and is linked from here.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "ecosystem.json").read_text())
segments = data["segments"]

MAX_SUBS = 6
MAX_EXAMPLES = 4


def collect_examples(node, out):
    for ex in node.get("examples", []) or []:
        out.append(ex)
    for c in node.get("children", []) or []:
        collect_examples(c, out)


def count_examples(node):
    out = []
    collect_examples(node, out)
    return len(out)


def count_subs(node):
    kids = node.get("children", []) or []
    return len(kids) + sum(count_subs(k) for k in kids)


def ex_link(ex):
    if ex.get("url"):
        return f"[{ex['name']}]({ex['url']})"
    return ex["name"]


def sub_chips(seg):
    kids = seg.get("children", []) or []
    names = [k["name"] for k in kids]
    if not names:
        return "—"
    shown = names[:MAX_SUBS]
    chips = " · ".join(f"`{n}`" for n in shown)
    if len(names) > MAX_SUBS:
        chips += f" · +{len(names) - MAX_SUBS}"
    return chips


def ex_cell(seg):
    out = []
    collect_examples(seg, out)
    if not out:
        return "—"
    shown = out[:MAX_EXAMPLES]
    rendered = ", ".join(ex_link(e) for e in shown)
    if len(out) > MAX_EXAMPLES:
        rendered += f", +{len(out) - MAX_EXAMPLES}"
    return rendered


lines = [
    "# Agentic AI Ecosystem Map",
    "",
    "A hand-curated **taxonomy** of the agentic AI ecosystem — categories, sub-areas, and representative projects as evidence that each functional slot exists. This is a classification map, not a project directory.",
    "",
    "- **Full taxonomy tree**: [SCHEMA.md](./SCHEMA.md) *(generated)*",
    "- **Source of truth**: [`graph/nodes.json`](./graph/nodes.json) + [`graph/edges.json`](./graph/edges.json)",
    "- **Derived tree view**: [`ecosystem.json`](./ecosystem.json)",
    "- **Interactive 3D viz**: [danielrosehill.github.io/Agentic-AI-Ecosystem/viz/](https://danielrosehill.github.io/Agentic-AI-Ecosystem/viz/)",
    "- **Sister project — runtime architecture model**: [Agentic-AI-Architecture-Visualisation](https://github.com/danielrosehill/Agentic-AI-Architecture-Visualisation)",
    "",
    "## At a glance",
    "",
    f"**{len(segments)}** top-level clusters · "
    f"**{sum(count_subs(s) for s in segments)}** sub-areas · "
    f"**{sum(count_examples(s) for s in segments)}** example projects.",
    "",
    "## Clusters",
    "",
    "Each row is a top-level functional cluster. Sub-areas and examples are truncated — see [SCHEMA.md](./SCHEMA.md) for the complete tree.",
    "",
    "| Cluster | What it covers | Sub-areas | Example projects |",
    "| --- | --- | --- | --- |",
]

for s in sorted(segments, key=lambda x: x["name"].lower()):
    desc = (s.get("short_description") or s.get("description") or "").strip().replace("|", "\\|")
    lines.append(f"| **{s['name']}** | {desc or '—'} | {sub_chips(s)} | {ex_cell(s)} |")

lines += [
    "",
    "---",
    "",
    "*README generated from `ecosystem.json` by `scripts/generate_readme.py`. Full tree generated into `SCHEMA.md` by `scripts/generate_schema.py`.*",
    "",
]

(ROOT / "README.md").write_text("\n".join(lines))
print(f"wrote README.md ({len(segments)} clusters)")
