#set document(title: "Agentic AI Ecosystem Taxonomy")
#set page(paper: "a4", margin: (x: 1.6cm, y: 1.8cm), numbering: "1 / 1")
#set text(font: "DejaVu Sans", size: 10pt)
#set par(justify: true, leading: 0.55em)

#align(center)[#text(size: 22pt, weight: "bold", fill: rgb("#1a365d"))[Agentic AI Ecosystem]]
#align(center)[#text(size: 11pt, fill: rgb("#4a5568"))[A hand-curated taxonomy of the agentic AI tooling landscape]]
#align(center)[#text(size: 9pt, fill: rgb("#718096"))[Generated from ecosystem.json · updated 2026-04-09]]
#v(1em)
#line(length: 100%, stroke: 0.5pt + rgb("#cbd5e0"))
#v(0.5em)
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Product analytics for agent behaviour: funnels, retention, conversation quality, task success.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Systems that run many agents together as a managed group or fleet.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* IntentKit]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Protocols, patterns and platforms for agents to collaborate on shared tasks.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentVerse]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Communication protocols and transports that let agents talk directly to other agents.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentChattr, ConnectOnion, OpenAgents]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Experimental agent-to-agent communication projects that don't fit established transport or protocol categories.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Research-grade and exploratory work on how agents might talk to each other — novel channels, encodings, or interaction modes. Sits alongside formal A2A protocols as a sandbox for ideas that haven't hardened into standards.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Audio-channel experiments where agents communicate via sound rather than text or structured messages.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Projects exploring voice or acoustic signaling as an inter-agent transport — agents emitting tones, speech, or compressed audio protocols to exchange information. A narrow experimental slot within agent-to-agent research.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Gibberlink]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools and services that agents invoke as capabilities, rather than frameworks for building agents themselves.]]
#block(inset: (left: 8pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Top-level segment for utilities designed to be called by agents — communications, side-effect actions, and similar capability providers. Distinct from runtimes, frameworks, or harnesses; these are the things at the other end of a tool call.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Messaging and communication tools that agents use to send, receive, or coordinate via human-style channels.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Services exposing email, chat, or mailbox-like primitives to agents as callable tools. Typically shipped as MCP servers or SDKs so an agent can send messages, read inboxes, and coordinate over standard comms channels.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MCP Agent Mail]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General agent projects and agent subtypes that do not fit more specific segments.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Xata Agent]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Long-running autonomous agents that pursue goals with minimal human supervision.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agents designed to operate open-endedly against a goal, planning and executing over extended horizons without turn-by-turn prompting. Distinct from chat assistants, harnesses, or task-specific agents — the defining trait is self-directed operation.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Autonomous agents that execute trading strategies in financial or crypto markets.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Self-directed agents that monitor markets, form views, and place trades without per-decision human approval. Typically shipped as runnable services or bots wired into exchange APIs.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AI-Trader]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents (or platforms) whose purpose is to spawn and configure other autonomous agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Meta-level tools where the output is a new agent — skill bundles, agent factories, or systems that compose runnable agents from specs. Sits above individual agents in the stack as a creation layer.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* BankrBot Skills]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Self-hostable backend platforms for building, deploying, and serving LLM-powered agents and apps.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Full-stack platforms — usually open source, often with a UI — that provide workflow, RAG, tool, and model plumbing behind an API. Contrast with libraries (frameworks) or managed SaaS: these are deployable services developers run to host agent applications.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Dify]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Command-line agents and developer toolkits for running agents from the terminal.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[CLI-first agent surfaces — coding agents, general assistants, and SDK-style toolkits invoked from a shell. Sits at the developer-interface layer of the stack, distinct from web frontends or backend services.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Vendor-published official CLI agents shipped by model providers as first-party terminal tools.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Official command-line agents released by the companies that train or host the underlying models. Distinguished from community CLIs by being the canonical vendor distribution.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Qwen Code]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents and frameworks that operate a computer the way a human would (mouse, keyboard, screen).]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* open-computer-use]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Desktop graphical interfaces for interacting with agents.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Hello Halo]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Software-engineering agents that read, write, and modify code to complete development tasks.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agents purpose-built for coding work — repo navigation, patch generation, test running, PR authoring. Distinct from general assistants by their tight integration with code, shells, and dev-loop feedback.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenHands]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents specialised for a particular vertical or professional domain rather than general use.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Parent slot for agents whose value comes from domain expertise — biotech, legal, finance, and similar. Children split by the specific field; membership implies the agent is meaningfully tailored to that domain's data, tools, or workflows.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents specialised for biotech, bioinformatics, and life-sciences research workflows.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agents built to assist with biology and biotech tasks such as literature mining, sequence analysis, lab protocol generation, and experiment planning. They typically wrap domain tools and datasets behind an LLM-driven interface.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Biomni]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General-purpose frameworks for building agents and agentic applications.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Open-source general-purpose agent frameworks under permissive or copyleft licences.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Freely available frameworks for building agents and agentic applications, distinguished from proprietary or hosted alternatives by their open codebases. They provide core loops, tool integration, and orchestration primitives developers can run and modify locally.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Hermes Agent]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[User-facing interfaces — web, desktop, mobile, terminal — for interacting with agents.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenClaw Mission Control]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Test harnesses and runner frameworks that host and exercise agents.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Command-line harnesses that host and run agents in a terminal environment.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[CLI-shaped runners that execute agents interactively or non-interactively from the shell. They sit at the execution layer of the stack, wrapping a model plus tools behind a terminal UX, and split into vendor-built and third-party implementations.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 36pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 44pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Third-party CLI harnesses not built by the underlying model vendor.]]
#block(inset: (left: 44pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Community or independent CLI runners that host agents against one or more model providers. They offer alternative terminal UXs and feature sets distinct from vendor-shipped CLIs.]]
#block(inset: (left: 44pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Crush]]
#block(above: 0.6em, below: 0.2em, inset: (left: 36pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 44pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Vendor-shipped CLI harnesses built by the model provider themselves.]]
#block(inset: (left: 44pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Official terminal agent runners published by the company behind the underlying model, such as Google's Gemini CLI or Anthropic's Claude Code. They provide a first-party execution surface tightly coupled to the vendor's models and APIs.]]
#block(inset: (left: 44pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Gemini CLI]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Memory systems for agents — short-term, long-term, episodic, file-backed, graph-backed.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Memory systems that construct and maintain knowledge graphs from agent interactions.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Tools that extract entities and relations from conversations, documents, or events and persist them as a graph used for long-term agent memory. They sit between raw logs and retrieval, turning unstructured history into structured, queryable memory.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Graphiti]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents built for a specific operational purpose that does not map to a domain vertical.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[A slot for agents defined by the task they perform (e.g. penetration testing, QA, triage) rather than by industry or framework. Distinguished from Domain Specific, which groups by vertical, and from Frameworks, which group by building blocks.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* INKOS]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents that autonomously perform offensive security and penetration testing tasks.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Security-focused agents that enumerate, probe, and exploit systems in a controlled way, chaining recon and exploitation tools under LLM direction. They sit alongside traditional pentesting frameworks as an autonomous execution layer.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Pentagi]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that assemble and configure multi-agent teams from roles or task descriptions.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Systems whose job is to decide which agents to spawn, with what roles, tools, and prompts, to tackle a given objective. They sit upstream of multi-agent runtimes, producing the team that another layer then executes.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Squad]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Preconfigured multi-agent teams targeting a specific workflow or domain.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Ready-made collections of cooperating agents wired together for a particular use case, such as data science or content production. Distinct from Team Formation (which builds teams) and from Frameworks (which provide the primitives).]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AI Data Science Team]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents whose primary modality is visual perception of images or video.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agents built around vision models that analyse, describe, or act on image and video inputs, often as part of a broader multimodal loop. They sit alongside text and computer-use agents as a distinct perceptual slot in the stack.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Vision Agents]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Browsers built or adapted specifically for AI agent use, including headless variants optimised for programmatic navigation.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* BrowserOS]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Headless browsers optimised for programmatic navigation by AI agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Browser engines without a visible UI, tuned for automated page loading, DOM access, and scraping under agent control. They sit below agent frameworks as the execution substrate for web interaction, competing with general-purpose headless tools repurposed for AI use.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Lightpanda Browser, Steel Browser]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Human labeling, RLHF, and feedback-collection platforms for agent training data.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General-purpose automation tools and frameworks, including GUI-driven and script-driven flows.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Open-source automation platforms and frameworks for building agentic workflows.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Self-hostable automation tools that power agent-driven workflows, spanning GUI-first builders and script-based engines. Sits alongside proprietary SaaS automation platforms but distinguished by open licensing and self-hosting.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Open-source visual/no-code builders for composing automation and agent workflows.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Drag-and-drop canvas tools where flows, triggers and agent steps are wired visually rather than in code. Typically self-hosted, targeting makers who want n8n/Zapier-style UX with open licensing.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Activepieces, Flowise]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that let agents query backend systems, databases and APIs.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MindsDB]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Standardised benchmarks for evaluating agent and model capabilities.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AICGSecEval, OSWorld]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Libraries and services for driving real browsers under agent control.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Vibium]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Utilities and SDKs that sit alongside browsers to support agentic workflows.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Browser, Stagehand]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents and frameworks that operate a computer the way a human would (mouse, keyboard, screen).]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* cua]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[CLI-based computer-use agents and tools.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* usecomputer]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Computer-use agents targeted at a specific operating system rather than cross-platform.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Groups computer-use implementations that exploit OS-native APIs, accessibility layers or UI conventions of one platform. Sits beside CLI and vision-based UI approaches as a delivery form factor for computer-use agents.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Computer-use agents built specifically for macOS desktops.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agents that drive macOS via AppleScript, Accessibility APIs, or native automation hooks to control apps and the desktop. Distinct from generic vision-based computer-use by leaning on Mac-specific primitives.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* cmux, macOS-use]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Vision-based UI understanding models for computer-use agents.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* UI-Venus]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools for building, optimising, managing and visualising the context window supplied to LLMs.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* PromptX, WeKnora]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that shrink, prioritise or restructure context before it reaches the model.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Middleware focused on making the context window more efficient — pruning, compressing, reordering or mode-switching content for an LLM call. Sits between context assembly and the model itself.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* context-mode]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Runtime engines that assemble and serve context to agents on demand.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Backends that fetch, merge and format context from multiple sources into a prompt-ready payload. The server-side counterpart to context optimisation and visualisation tools.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Contexto]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Client-side tools for capturing or selecting context from a running UI.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Browser/app-side utilities that let users grab DOM fragments, components or page state and feed them into an agent. Typically a bridge between a live frontend and a context engine.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* react-grab]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Utility tools, SDKs and toolkits for building, debugging and extending agentic systems.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Utilities that organise, persist and version the context a developer feeds into coding agents.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Tooling for curating dotfile-style context bundles, rules and memory snippets used by AI coding assistants. Acts as a local source of truth for what gets injected into each session.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* dotai]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools for inspecting and visualising what is inside an LLM context window.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Debug and introspection utilities that render tokens, messages and attached artefacts so developers can see exactly what the model received. Complements context optimisation by exposing waste and overlap.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* context-lens]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Systems that steer or constrain multi-turn conversations with agents.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Parlant]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that convert unstructured data into structured form for agents to consume.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Firecrawl]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Curated data feeds and providers that agents can draw on.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Financial and markets data feeds exposed as tools or sources for agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Providers of equities, crypto, macro and company fundamentals data packaged for programmatic agent consumption. Sits in the data layer beneath research and trading agents.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenBB]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Database systems used in agentic stacks, including purpose-built context and vector stores.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Databases specifically designed for storing and retrieving agent/LLM context.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenViking]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Platforms for deploying and hosting agents and agentic services.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Serverless runtimes for hosting agents without managing long-lived infrastructure.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Platforms that run agent workflows on-demand with managed scaling, state and scheduling. Occupies the same slot as containerised agent hosts but with a function-style execution model.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Julep]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Developer tooling that uses agents or supports agent development workflows.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Debugging and introspection tools for agent development.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* vLLora]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[IDE extensions and plugins for agent-assisted development.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Roo-Code]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent-assisted tooling for restructuring and refactoring entire repositories.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Tools that apply large-scale, agent-driven transformations across a codebase — renames, moves, config migrations, architectural shifts. Distinct from IDE-level assistants by operating at repo scope.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentRC]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[End-to-end platforms for building agentic applications.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Coze Studio]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Models used to produce embeddings for retrieval and RAG pipelines.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Orchestration tools that manage embedding generation and ingestion pipelines.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Platforms targeted at engineering teams building with LLMs and agents.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* VoltAgent]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Sandboxed environments — OS, simulated worlds, virtual machines — in which agents run.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent-native operating systems providing a full OS abstraction for autonomous agents to run within.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[OS-level environments purpose-built as runtimes for agents, exposing processes, filesystem, and system calls as primitives the agent can control. Sits below frameworks and harnesses as the host substrate.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* agent-os]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Hosted remote desktop / VM services providing agents with a persistent GUI environment to operate.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Abacus Desktop, cua.ai]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks, harnesses and platforms for evaluating agents and tracking experiments.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* LangWatch, TruLens]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General-purpose frameworks for building agents and agentic applications.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* DeepEval]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Logging, tracing and observability specifically for agent and LLM systems.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Langfuse]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that shape feedback signals (tool output, user input) into forms agents can act on.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agentation]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent-oriented tools targeted at financial workflows.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentKit, GOAT]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Token-efficient serialisation and data-formatting schemes for passing structured data to and from LLMs.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* TOON]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Industry foundations, consortia and non-profits shaping the agentic AI ecosystem.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agentic AI Industry Foundation (AAIF)]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General-purpose frameworks for building agents and agentic applications.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentForge, AIOpsLab, AutoGen, EvoAgentX, II-Agent, Langflow, uAgents, Vercel AI SDK]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[.NET/C\# agent frameworks for building agents in the Microsoft ecosystem.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agent-building frameworks targeting the .NET runtime and C\# developers. Provides idiomatic APIs, DI, and tooling for embedding LLM agents into .NET applications and services.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* BotSharp]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents and frameworks that operate a computer the way a human would (mouse, keyboard, screen).]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent-S]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks for coordinating multiple cooperating agents with roles, messaging, and task delegation.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Frameworks whose primary abstraction is a team of agents: role assignment, inter-agent messaging, shared state, and task routing. Used to compose workflows where specialised agents collaborate rather than a single monolithic agent.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* CAMEL, CrewAI]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent frameworks with first-class support for non-text modalities such as audio, image, and video.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Frameworks designed around multimodal input and output — video, image, audio streams — rather than text-only chat. Handles media I/O plumbing, streaming, and model routing for agents that perceive or produce rich media.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* VideoSDK Agents]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks focused on optimising agent execution — latency, cost, throughput, parallelism.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Frameworks whose differentiator is execution efficiency rather than abstractions for authoring agents. Covers parallel dispatch, batching, and cost/latency tradeoffs.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks that parallelise agent or subtask execution across workers for throughput.]]
#block(inset: (left: 32pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Tools that fan out agent work — steps, tool calls, or whole agent runs — across parallel workers. Targets throughput-bound workloads where serial agent loops are the bottleneck.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* EnsoAI]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks for simulating populations of agents modelling social, economic, or behavioural dynamics.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Frameworks for agent-based social simulation: many LLM-backed personas interacting under rules to study emergent group behaviour. Used for research, game-like worlds, and counterfactual studies rather than task execution.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Concordia, Moltbook]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks built around persistent, long-lived agent state and memory as the core abstraction.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Frameworks where durable agent state — memory, identity, long-running context — is the central primitive rather than a bolt-on. Agents persist across sessions and evolve their internal state over time.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Letta]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Voice-first agents and voice interaction frameworks.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* LiveKit Agents, TEN Framework]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[User-facing interfaces — web, desktop, mobile, terminal — for interacting with agents.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Native Android apps that serve as frontends for interacting with agents on mobile.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Android-specific client applications for chatting with and operating agents from a phone. Handles mobile UX, background behaviour, and on-device integrations distinct from web or desktop clients.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Operit]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Web or desktop chat interfaces purpose-built as frontends for agents rather than plain LLMs.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Chat-style user interfaces tailored for agent interaction — tool call rendering, step traces, artefact display — rather than generic LLM chat. Typically web-based and framework-agnostic on the backend.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent UI]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Dual GUI-and-CLI agent clients offering both graphical and command-line interaction modes.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agent frontends that ship as both a graphical desktop app and a command-line tool, sharing a backend. Lets users pick interaction style per task without switching agents.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Goose]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Terminal user interfaces and command-line clients for interacting with agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Text-mode frontends — TUIs and CLIs — for driving agents from the terminal. Favoured by developers for scriptability, low overhead, and integration into shell workflows.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Deck]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Gateway services that sit between agents and upstream services (LLMs, tools, data).]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Gateways that compress or distill context before it reaches the model.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Proxy-layer services that sit between agents and LLMs to shrink prompts, summarize history, or prune tool output, reducing token spend and latency. Distinct from memory systems in that they operate inline on the request path rather than storing state.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Context-Gateway]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Simulations focused specifically on geopolitical scenarios and dynamics.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Snowglobe, WargamesAI]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Guardrails and pre-execution safety checks that gate what running agents can do.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Shellfirm]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Execution-layer scaffolding that wraps agents for real runs — sub-agent dispatch, long-horizon coherence, checkpointing, platform-specific runtimes.]]
#block(inset: (left: 8pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Harnesses sit between frameworks (which define agent shape) and runtimes (which provide the sandbox). They're the execution-layer utilities that make long-running, multi-step agent runs actually work in practice: spawning isolated sub-agent contexts, resuming from checkpoints, recovering from tool failures, keeping the main thread coherent over time, and adapting to the host platform.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Hive, oh-my-openagent]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Save and restore agent execution state across interruptions, crashes, or session boundaries.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Harness-level summarisation and pruning that rolls the context window during a run, distinct from gateway-level compression in the request path.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Harnesses for multi-step research workflows with planning, tool use, and synthesis.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* DeepAgents]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Harnesses that target a specific host OS or environment for native integration.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Harnesses that run agents natively on macOS.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Osaurus]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Failure handling, automatic rerun on tool errors, and partial-result recovery for agent loops.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Libraries and runtimes that spawn isolated sub-agent contexts to offload work and preserve main-thread coherence.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Progress trackers, self-reflection loops, and plan-revision utilities that keep long-running agent tasks on course.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent identity, credential vaulting, and delegated authentication for tool access.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[LLM inference servers and runtimes (vLLM, TGI, llama.cpp, SGLang) that agents call into.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent-to-SaaS connector platforms: Composio-style libraries exposing third-party APIs as agent tools.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Composio]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Language models, including those trained or tuned specifically for agentic use cases.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Gemini 3.1]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[LLMs trained or tuned specifically for agentic and multi-agent workloads.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Models whose training objective, post-training, or native harness targets tool use, planning, or multi-agent coordination rather than general chat. Sits at the model layer of the stack and is chosen when vanilla instruction-tuned models fall short on agent benchmarks.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Grok 4.20 Multi-Agent]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[LLMs grouped by the agentic use case they are optimized for.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Organizes models by the downstream agentic task they target — computer use, coding, browsing, and so on — rather than by vendor or size. A parent bucket whose children are the specific use-case slots.]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents and frameworks that operate a computer the way a human would (mouse, keyboard, screen).]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Fara]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent loop implementations — the core think/act/observe cycle.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Ralph]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Marketplaces and stores for discovering, listing, or transacting agents and agent-based services.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* agen.cy Marketplace, AI Agent Store]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Projects in the Model Context Protocol ecosystem — servers, gateways, aggregators, clients.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Aggregators that bundle many MCP servers behind a single endpoint.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Meta-MCP services that expose dozens or hundreds of upstream MCP servers through one unified connection, handling discovery, auth, and routing. Reduces per-client configuration burden when an agent needs access to a broad tool surface.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Klavis]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Gateway services that sit between agents and upstream services (LLMs, tools, data).]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MCP Context Forge]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Community-built MCP servers wrapping third-party SaaS and APIs.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Unofficial MCP server implementations that expose external products and APIs (Airbnb, Spotify, etc.) as MCP tools, built outside the vendor. The catch-all slot for community MCP coverage of commercial services.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MCP Server Airbnb]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Memory systems for agents — short-term, long-term, episodic, file-backed, graph-backed.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentMemory, Cognee, Mem0, MemOS]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[File-backed memory stores for agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Memory backends that persist agent state to files — flat, encoded, or media-container formats — rather than databases or vector stores. Useful for portable, inspectable, or offline agent memory.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Memvid]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Memory that refines itself by regressing over past interactions.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Memory systems that iteratively re-process prior context to extract, correct, or compress learned signal, rather than just appending new entries. Targets long-running agents whose context quality must improve over time.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agentic Context Engine]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent skills ecosystems — registries, bundles, standards, guides and package libraries.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Acontext]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Systems built around multiple cooperating or competing agents.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Frameworks for running simulations with thousands of agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Engines built to scale multi-agent populations into the thousands or millions for social, economic, or emergent-behavior experiments. Distinct from production orchestration — the goal is research and simulation, not task delivery.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentTorch]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Swarms of agents aggregated to produce forecasts or predictions.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Multi-agent systems where many independent agents vote, bid, or debate to generate a collective prediction, mimicking prediction-market or wisdom-of-crowds dynamics. The output is a forecast signal rather than a completed task.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MiroFish]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent networks and directories — social/professional platforms where agents and their creators are listed and interconnected.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* agent.ai]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Logging, tracing and observability specifically for agent and LLM systems.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* RagaAI Catalyst]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents designed to run on-device, including phones, SBCs and edge hardware.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Android-specific agent runtimes and device-level automation.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Device]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent runtimes targeting single-board computers and edge hardware.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agent stacks built for Raspberry Pi class boards and similar SBCs, optimized for constrained CPU, RAM, and power budgets. Sibling to phone-specific runtimes in the on-device layer.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* be-more-agent]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Operational concerns for running agents in production — cost, monitoring, reliability.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that track token spend and cost for production agents.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Observability systems focused on financial metrics — per-run, per-agent, and per-tool cost attribution for LLM and tool calls. Distinct from general tracing or evals; the primary surface is a spend dashboard.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentOps]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Platforms focused on optimising agent/LLM pipelines.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Coze Loop]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Orchestration engines for coordinating agents, tools and workflows.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Orchestrator, AI Maestro, Conductor, Shannon]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Orchestration frameworks tied to a specific cloud or vendor platform.]]
#block(inset: (left: 20pt), below: 0.3em)[#text(size: 8.5pt, fill: rgb("#2d3748"))[Agent orchestration engines that are coupled to one provider's runtime, SDKs, or services rather than being platform-neutral. Chosen when a team has already committed to that platform's ecosystem.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Squad]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Personal AI assistants and related projects.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Crucix, Nanobot]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Leon, OpenClaw]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools for giving agents distinct personas, voices and identities.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Bub]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[PII detection, content sanitization, and safety filtering for agent I/O.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Reusable pipelines for common agentic workloads.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Paper2Agent]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General platforms that host or enable agentic applications.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Fairo]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Versioning, registries, and lifecycle management for prompts as first-class artifacts.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Proxy services that sit between clients and LLM/agent backends.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Gateway services that sit between agents and upstream services (LLMs, tools, data).]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentGateway, LiteLLM]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* MCPO]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Retrieval-augmented generation engines, frameworks and components.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Airweave]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* RAGFlow]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Pipelines that ingest and process documents into retrieval systems.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent-Reach]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[RL frameworks and environments used to train agentic behaviour.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Acme, RLinf]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Routing layers that select between models, tools or agents based on cost, capability or intent.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* RelayPlane Proxy]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agentic Flow, Semantic Router]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* ClawRouter]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Execution runtimes — sandboxes, data layers, kernels — that host running agents.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenShell]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Deep Lake]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Runtime policy engines that evaluate and enforce rules on agent actions.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Aegis]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OpenSandbox]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Hosted SaaS platforms for building agents and agentic workflows, spanning no-code, visual, and code-defined paradigms.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Hosted builders where agents and workflows are primarily defined in code (SDK, DSL, or config-as-code).]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Builders targeted at non-programmers, typically form- and config-driven with minimal visual wiring.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Builders where flows are expressed as node-and-edge graphs or canvas-based visual programs.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* n8n]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Visual builders oriented around structured, multi-step workflows rather than free-form agents.]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Gumloop, MindStudio]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Security tooling for agents: sandboxing, red teaming, defensive automation.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* agent-scan, AgentGuard]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[General-purpose automation tools and frameworks, including GUI-driven and script-driven flows.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Tracecat]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Centralised control planes for governing, auditing, and enforcing policy across agent fleets.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Cordum]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Rogue]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Microsandbox]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Cache layers that serve semantically equivalent LLM responses to cut cost and latency.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Semantic search tools for agents operating over codebases and local content.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* osgrep]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agent skills ecosystems — registries, bundles, standards, guides and package libraries.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Skills]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(above: 0.6em, below: 0.2em, inset: (left: 24pt))[#text(size: 10.5pt, weight: "bold", fill: rgb("#4a5568"))[]]
#block(inset: (left: 32pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Marketing Skills]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Taste Skill]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Vercel Skills]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Skills (tech-leads-club)]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Proposed and emerging standards across the agentic ecosystem.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentSkills]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Large-scale simulations of societies and human behaviour using agent populations.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* OASIS]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Extensions and plugins that add agentic capabilities to existing software.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Jupyter AI]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Proposed and emerging standards across the agentic ecosystem.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Emerging standards whose adoption is tied to a specific host ecosystem (e.g. a browser engine or platform vendor) rather than being fully vendor-neutral.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* WebMCP, WebMCP (Chrome EPP)]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AIUC-1, GitAgent]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Standards with a published specification and active governance.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* A2A (Agent2Agent Protocol), AG-UI (Agent User Interaction Protocol), MCP (Model Context Protocol)]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Opinionated starter kits and templates for kicking off agentic projects.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AI Town]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Libraries that constrain LLM outputs to typed schemas, JSON, or formal grammars.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that synthesise multiple viewpoints or agent outputs into a unified perspective.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* LLM Council, Plurals]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools for generating synthetic training and evaluation data for agents.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Agents and tools built for a single specific task rather than general use.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Superdesign]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Training frameworks and tools for agent models.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Lightning]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Holding area for projects awaiting classification. Entries here are a todo list, not a destination.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agency Agents]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools that manage upserting data into vector stores and retrieval indexes.]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[User-experience patterns and components specifically for agent systems.]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Interfaces and workflows for inserting humans into agent execution — approvals, task handoff, review queues.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Agent Inbox, Orchestra]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Vector databases used for embedding storage and similarity search.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Qdrant]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Voice-first agents and voice interaction frameworks.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Bolna]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools and DSLs for authoring agent workflows as first-class, portable artifacts.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Packmind]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Shared workspaces where agents and humans (or multiple agents) collaborate.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* AgentsMesh, Gastown, LobeHub]]
#block(above: 1.2em, below: 0.4em)[#text(size: 14pt, weight: "bold", fill: rgb("#1a365d"))[]]
#block(inset: (left: 8pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[Tools and models for generating simulated worlds for agents to operate in.]]
#block(inset: (left: 8pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* ML-Agents]]
#block(above: 0.8em, below: 0.3em, inset: (left: 12pt))[#text(size: 12pt, weight: "bold", fill: rgb("#2b6cb0"))[]]
#block(inset: (left: 20pt), below: 0.2em)[#text(size: 9pt, style: "italic", fill: rgb("#4a5568"))[MCP servers for world and scene generation.]]
#block(inset: (left: 20pt), below: 0.4em)[#text(size: 8.5pt, fill: rgb("#2f855a"))[*Examples:* Unreal Engine MCP]]